/*
 * 
 * This is the mysql db create script. 
 * Warning this script will drop the entire database.
 * Run using...
 * 
 * $ mysql -u username -p < create-db.sql
 * 
 * Warning: this will drop the existing database
 * 
 */

-- MySQL Script generated by MySQL Workbench
-- Fri 05 Feb 2016 07:22:33 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rvep
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rvep` ;

-- -----------------------------------------------------
-- Schema rvep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rvep` DEFAULT CHARACTER SET utf8 ;
USE `rvep` ;

-- -----------------------------------------------------
-- Table `rvep`.`rvep_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_event` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `enabled` TINYINT(1) NOT NULL,
  `created_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`event_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`event_profile` ;

CREATE TABLE IF NOT EXISTS `rvep`.`event_profile` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(36) NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  `picture` VARBINARY(1000) NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  `is_open_enrollment` TINYINT(1) NOT NULL,
  `hash_id` VARCHAR(255) NOT NULL,
  `person_limit` INT(11) NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `rvep_event_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_profile_rvep_event1_idx` (`rvep_event_id` ASC),
  CONSTRAINT `fk_event_profile_rvep_event1`
    FOREIGN KEY (`rvep_event_id`)
    REFERENCES `rvep`.`rvep_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`role_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`role_category` ;

CREATE TABLE IF NOT EXISTS `rvep`.`role_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(36) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1101
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_user` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `enabled` TINYINT(1) NOT NULL,
  `created_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rolling_vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rolling_vote` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rolling_vote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `value` TINYINT(1) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `rvep_user_id` INT(11) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rolling_vote_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_rolling_vote_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_chip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_chip` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_chip` (
  `chip` VARBINARY(64) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rvep_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rvep_chip_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_rvep_chip_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_location` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_location` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(36) NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  `geolat` FLOAT(10,6) NOT NULL,
  `geolng` FLOAT(10,6) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`todo_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`todo_list` ;

CREATE TABLE IF NOT EXISTS `rvep`.`todo_list` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(36) NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `rvep_event_id` INT(11) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_todo_list_rvep_event1_idx` (`rvep_event_id` ASC),
  CONSTRAINT `fk_todo_list_rvep_event1`
    FOREIGN KEY (`rvep_event_id`)
    REFERENCES `rvep`.`rvep_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_event_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_event_item` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_event_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  `title` VARCHAR(36) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `rvep_event_id` INT(11) NOT NULL,
  `rvep_location_id` INT(11) NOT NULL,
  `todo_list_id` INT(11) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rvep_event_item_rvep_event1_idx` (`rvep_event_id` ASC),
  INDEX `fk_rvep_event_item_rvep_location1_idx` (`rvep_location_id` ASC),
  INDEX `fk_rvep_event_item_todo_list1_idx` (`todo_list_id` ASC),
  CONSTRAINT `fk_rvep_event_item_rvep_event1`
    FOREIGN KEY (`rvep_event_id`)
    REFERENCES `rvep`.`rvep_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_event_item_rvep_location1`
    FOREIGN KEY (`rvep_location_id`)
    REFERENCES `rvep`.`rvep_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_event_item_todo_list1`
    FOREIGN KEY (`todo_list_id`)
    REFERENCES `rvep`.`todo_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_role` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(36) NOT NULL,
  `role_category_id` INT(11) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_rvep_role_role_category_idx` (`role_category_id` ASC),
  CONSTRAINT `fk_rvep_role_role_category`
    FOREIGN KEY (`role_category_id`)
    REFERENCES `rvep`.`role_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`suggestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`suggestion` ;

CREATE TABLE IF NOT EXISTS `rvep`.`suggestion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(140) NOT NULL,
  `title` VARCHAR(36) NOT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `rvep_user_id` INT(11) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suggestion_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_suggestion_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`todo_list_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`todo_list_item` ;

CREATE TABLE IF NOT EXISTS `rvep`.`todo_list_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(36) NOT NULL,
  `description` VARCHAR(140) NOT NULL,
  `todo_list_id` INT(11) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_todo_list_item_todo_list1_idx` (`todo_list_id` ASC),
  CONSTRAINT `fk_todo_list_item_todo_list1`
    FOREIGN KEY (`todo_list_id`)
    REFERENCES `rvep`.`todo_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`user_profile` ;

CREATE TABLE IF NOT EXISTS `rvep`.`user_profile` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(36) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `description` VARCHAR(140) NULL DEFAULT NULL,
  `picture` VARBINARY(1000) NULL DEFAULT NULL,
  `first_name` VARCHAR(36) NULL DEFAULT NULL,
  `last_name` VARCHAR(36) NULL DEFAULT NULL,
  `last_login` DATETIME NOT NULL,
  `rvep_user_id` INT(11) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `userProfileOnEmail` (`email` ASC),
  INDEX `userProfileOnUsername` (`username` ASC),
  INDEX `fk_user_profile_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_user_profile_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`user_role` ;

CREATE TABLE IF NOT EXISTS `rvep`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rvep_role_id` INT(11) NOT NULL,
  `rvep_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_rvep_role1_idx` (`rvep_role_id` ASC),
  INDEX `fk_user_role_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_user_role_rvep_role1`
    FOREIGN KEY (`rvep_role_id`)
    REFERENCES `rvep`.`rvep_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rvep`.`user_event_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`user_event_role` ;

CREATE TABLE IF NOT EXISTS `rvep`.`user_event_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rvep_role_id` INT(11) NOT NULL,
  `rvep_user_id` INT(11) NOT NULL,
  `rvep_event_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_event_role_rvep_role1_idx` (`rvep_role_id` ASC),
  INDEX `fk_user_event_role_rvep_user1_idx` (`rvep_user_id` ASC),
  INDEX `fk_user_event_role_rvep_event1_idx` (`rvep_event_id` ASC),
  CONSTRAINT `fk_user_event_role_rvep_role1`
    FOREIGN KEY (`rvep_role_id`)
    REFERENCES `rvep`.`rvep_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_event_role_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_event_role_rvep_event1`
    FOREIGN KEY (`rvep_event_id`)
    REFERENCES `rvep`.`rvep_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_event_suggestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_event_suggestion` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_event_suggestion` (
  `rvep_event_id` INT(11) NOT NULL,
  `suggestion_id` INT(11) NOT NULL,
  PRIMARY KEY (`rvep_event_id`, `suggestion_id`),
  INDEX `fk_rvep_event_suggestion_suggestion1_idx` (`suggestion_id` ASC),
  INDEX `fk_rvep_event_suggestion_rvep_event1_idx` (`rvep_event_id` ASC),
  CONSTRAINT `fk_rvep_event_suggestion_rvep_event1`
    FOREIGN KEY (`rvep_event_id`)
    REFERENCES `rvep`.`rvep_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_event_suggestion_suggestion1`
    FOREIGN KEY (`suggestion_id`)
    REFERENCES `rvep`.`suggestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_event_item_suggestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_event_item_suggestion` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_event_item_suggestion` (
  `rvep_event_item_id` INT(11) NOT NULL,
  `suggestion_id` INT(11) NOT NULL,
  PRIMARY KEY (`rvep_event_item_id`, `suggestion_id`),
  INDEX `fk_rvep_event_item_suggestion_suggestion1_idx` (`suggestion_id` ASC),
  INDEX `fk_rvep_event_item_suggestion_rvep_event_item1_idx` (`rvep_event_item_id` ASC),
  CONSTRAINT `fk_rvep_event_item_suggestion_rvep_event_item1`
    FOREIGN KEY (`rvep_event_item_id`)
    REFERENCES `rvep`.`rvep_event_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_event_item_suggestion_suggestion1`
    FOREIGN KEY (`suggestion_id`)
    REFERENCES `rvep`.`suggestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rolling_vote_rvep_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rolling_vote_rvep_event` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rolling_vote_rvep_event` (
  `rolling_vote_id` INT(11) NOT NULL,
  `rvep_event_id` INT(11) NOT NULL,
  PRIMARY KEY (`rolling_vote_id`, `rvep_event_id`),
  INDEX `fk_rolling_vote_rvep_event_rvep_event1_idx` (`rvep_event_id` ASC),
  INDEX `fk_rolling_vote_rvep_event_rolling_vote1_idx` (`rolling_vote_id` ASC),
  CONSTRAINT `fk_rolling_vote_rvep_event_rolling_vote1`
    FOREIGN KEY (`rolling_vote_id`)
    REFERENCES `rvep`.`rolling_vote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rolling_vote_rvep_event_rvep_event1`
    FOREIGN KEY (`rvep_event_id`)
    REFERENCES `rvep`.`rvep_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rolling_vote_suggestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rolling_vote_suggestion` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rolling_vote_suggestion` (
  `rolling_vote_id` INT(11) NOT NULL,
  `suggestion_id` INT(11) NOT NULL,
  PRIMARY KEY (`rolling_vote_id`, `suggestion_id`),
  INDEX `fk_rolling_vote_suggestion_suggestion1_idx` (`suggestion_id` ASC),
  INDEX `fk_rolling_vote_suggestion_rolling_vote1_idx` (`rolling_vote_id` ASC),
  CONSTRAINT `fk_rolling_vote_suggestion_rolling_vote1`
    FOREIGN KEY (`rolling_vote_id`)
    REFERENCES `rvep`.`rolling_vote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rolling_vote_suggestion_suggestion1`
    FOREIGN KEY (`suggestion_id`)
    REFERENCES `rvep`.`suggestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rolling_vote_rvep_event_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rolling_vote_rvep_event_item` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rolling_vote_rvep_event_item` (
  `rolling_vote_id` INT(11) NOT NULL,
  `rvep_event_item_id` INT(11) NOT NULL,
  PRIMARY KEY (`rolling_vote_id`, `rvep_event_item_id`),
  INDEX `fk_rolling_vote_rvep_event_item_rvep_event_item1_idx` (`rvep_event_item_id` ASC),
  INDEX `fk_rolling_vote_rvep_event_item_rolling_vote1_idx` (`rolling_vote_id` ASC),
  CONSTRAINT `fk_rolling_vote_rvep_event_item_rolling_vote1`
    FOREIGN KEY (`rolling_vote_id`)
    REFERENCES `rvep`.`rolling_vote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rolling_vote_rvep_event_item_rvep_event_item1`
    FOREIGN KEY (`rvep_event_item_id`)
    REFERENCES `rvep`.`rvep_event_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`user_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`user_contact` ;

CREATE TABLE IF NOT EXISTS `rvep`.`user_contact` (
  `rvep_user_id` INT(11) NOT NULL,
  `user_profile_id` INT(11) NOT NULL,
  PRIMARY KEY (`rvep_user_id`, `user_profile_id`),
  INDEX `fk_rvep_user_user_profile_user_profile1_idx` (`user_profile_id` ASC),
  INDEX `fk_rvep_user_user_profile_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_rvep_user_user_profile_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_user_user_profile_user_profile1`
    FOREIGN KEY (`user_profile_id`)
    REFERENCES `rvep`.`user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`invite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`invite` ;

CREATE TABLE IF NOT EXISTS `rvep`.`invite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL,
  `accepted` TINYINT(1) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_user_invite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_user_invite` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_user_invite` (
  `rvep_user_id` INT(11) NOT NULL,
  `invite_id` INT NOT NULL,
  PRIMARY KEY (`rvep_user_id`, `invite_id`),
  INDEX `fk_rvep_user_invite_invite1_idx` (`invite_id` ASC),
  INDEX `fk_rvep_user_invite_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_rvep_user_invite_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_user_invite_invite1`
    FOREIGN KEY (`invite_id`)
    REFERENCES `rvep`.`invite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_event_invite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_event_invite` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_event_invite` (
  `rvep_event_id` INT(11) NOT NULL,
  `invite_id` INT NOT NULL,
  PRIMARY KEY (`rvep_event_id`, `invite_id`),
  INDEX `fk_rvep_event_invite_invite1_idx` (`invite_id` ASC),
  INDEX `fk_rvep_event_invite_rvep_event1_idx` (`rvep_event_id` ASC),
  CONSTRAINT `fk_rvep_event_invite_rvep_event1`
    FOREIGN KEY (`rvep_event_id`)
    REFERENCES `rvep`.`rvep_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_event_invite_invite1`
    FOREIGN KEY (`invite_id`)
    REFERENCES `rvep`.`invite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_user_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_user_event` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_user_event` (
  `rvep_user_id` INT(11) NOT NULL,
  `rvep_event_id` INT(11) NOT NULL,
  PRIMARY KEY (`rvep_user_id`, `rvep_event_id`),
  INDEX `fk_rvep_user_rvep_event_rvep_event1_idx` (`rvep_event_id` ASC),
  INDEX `fk_rvep_user_rvep_event_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_rvep_user_rvep_event_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_user_rvep_event_rvep_event1`
    FOREIGN KEY (`rvep_event_id`)
    REFERENCES `rvep`.`rvep_event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`event_item_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`event_item_task` ;

CREATE TABLE IF NOT EXISTS `rvep`.`event_item_task` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `rvep_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_item_task_rvep_user1_idx` (`rvep_user_id` ASC),
  CONSTRAINT `fk_event_item_task_rvep_user1`
    FOREIGN KEY (`rvep_user_id`)
    REFERENCES `rvep`.`rvep_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rvep`.`rvep_event_item_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`rvep_event_item_task` ;

CREATE TABLE IF NOT EXISTS `rvep`.`rvep_event_item_task` (
  `rvep_event_item_id` INT(11) NOT NULL,
  `event_item_task_id` INT(11) NOT NULL,
  PRIMARY KEY (`rvep_event_item_id`, `event_item_task_id`),
  INDEX `fk_rvep_event_item_event_item_task_event_item_task1_idx` (`event_item_task_id` ASC),
  INDEX `fk_rvep_event_item_event_item_task_rvep_event_item1_idx` (`rvep_event_item_id` ASC),
  CONSTRAINT `fk_rvep_event_item_event_item_task_rvep_event_item1`
    FOREIGN KEY (`rvep_event_item_id`)
    REFERENCES `rvep`.`rvep_event_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rvep_event_item_event_item_task_event_item_task1`
    FOREIGN KEY (`event_item_task_id`)
    REFERENCES `rvep`.`event_item_task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`todo_list_event_item_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`todo_list_event_item_task` ;

CREATE TABLE IF NOT EXISTS `rvep`.`todo_list_event_item_task` (
  `todo_list_id` INT(11) NOT NULL,
  `event_item_task_id` INT(11) NOT NULL,
  PRIMARY KEY (`todo_list_id`, `event_item_task_id`),
  INDEX `fk_todo_list_event_item_task_event_item_task1_idx` (`event_item_task_id` ASC),
  INDEX `fk_todo_list_event_item_task_todo_list1_idx` (`todo_list_id` ASC),
  CONSTRAINT `fk_todo_list_event_item_task_todo_list1`
    FOREIGN KEY (`todo_list_id`)
    REFERENCES `rvep`.`todo_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_list_event_item_task_event_item_task1`
    FOREIGN KEY (`event_item_task_id`)
    REFERENCES `rvep`.`event_item_task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rvep`.`todo_list_item_event_item_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rvep`.`todo_list_item_event_item_task` ;

CREATE TABLE IF NOT EXISTS `rvep`.`todo_list_item_event_item_task` (
  `todo_list_item_id` INT(11) NOT NULL,
  `event_item_task_id` INT(11) NOT NULL,
  PRIMARY KEY (`todo_list_item_id`, `event_item_task_id`),
  INDEX `fk_todo_list_item_event_item_task_event_item_task1_idx` (`event_item_task_id` ASC),
  INDEX `fk_todo_list_item_event_item_task_todo_list_item1_idx` (`todo_list_item_id` ASC),
  CONSTRAINT `fk_todo_list_item_event_item_task_todo_list_item1`
    FOREIGN KEY (`todo_list_item_id`)
    REFERENCES `rvep`.`todo_list_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_todo_list_item_event_item_task_event_item_task1`
    FOREIGN KEY (`event_item_task_id`)
    REFERENCES `rvep`.`event_item_task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
